### ISSUE TITLE
Log spam whilst dynamically processing slabs to Klee compat

### ISSUE THREAD

**Issue by NighthowlerStudios** [blay09/KleethoMod#47] opened 2021-12-19 18:28 UTC
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.22

### Mod Version

9.2.1

### Describe the Issue

The log will spam (insert slab block name here) "not found" whilst processing block registry when starting a world.
example line:
[19Dec2021 18:13:48.940] [Worker-Main7/ERROR] [net.blay09.mods.kleeslabs.KleeSlabs/]: Slab stained_clay_tiles_blue_slab could not be found.

### Logs

https://pastebin.com/d0Ug2L2M

### Do you use any performance-enhancing mods (e.g. OptiFine)?

yes, but seems irrelevant

**Comment by BlayTheNinth** [comment] 2021-12-27 20:11
Duplicate of #40

**Closed as completed by BlayTheNinth** 2021-12-27 20:11 UTC
Labels: Bug, Duplicate
