### ISSUE TITLE
Serious item disapearing issue

### ISSUE THREAD

**Issue by vgrynch** [blay09/KleethoMod#77] opened 2023-08-25 18:10 UTC
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

43.2.21

### Mod Version

12.3.0

### Balm Version

4.5.7

### Describe the Issue

When using custom slabs from certain unsupported mods, the mod does not work - that's right. However, after using the pick axe on a double-slab block, I'm getting only one(!) slab, not 2.

It's a serious issue. While we are waiting for you to add the support for another mod, why not have it working as a default behavior (break both slabs AND return 2 slabs, do not lose 1)?

Please, fix it.

**Comment by BlayTheNinth** [comment] 2023-09-03 18:14
KleeSlabs does not alter the dropping behaviour of slabs it has no support for. If you were to try breaking those particular slabs without KleeSlabs installed, you would very likely end with the same result. The issue lies in the mod adding those slabs, not KleeSlabs.

**Comment by vgrynch** [comment] 2023-09-08 07:31
@BlayTheNinth, I tried to do it without KleeSlabs and everything worked well - 2 slabs were returned. It looks to me much like KleeSlabs tries to be involved so 1 slab returns, however, both slabs break. Might be possibly related to the version upgrades in other mods.

**Comment by BlayTheNinth** [comment] 2023-09-12 11:39
Does that mean the issue is solved in the newer versions of those mods?

**Comment by vgrynch** [comment] 2023-09-12 15:20
No, I mean other mods changed something in 1.19.2, and KleeSlabs did not accomodate it. I noticed there are mods in my modpack that have certain slabs work well, while newer block slabs in that mod do not work.

**Comment by BlayTheNinth** [comment] 2023-09-12 15:33
What mods and blocks are affected?

**Comment by vgrynch** [comment] 2023-09-12 15:36
See https://github.com/TwelveIterationMods/KleeSlabs/issues/78
I listed there all mods I had in modpack at that moment and that had issues with KleeSlabs. I have added a few more recently, but did not try them with KleeSlabs yet.

**Comment by vgrynch** [comment] 2023-09-12 15:37
This ticket is not about the particular mod. This ticket is a request to improve general mechanics of the mod.

**Comment by BlayTheNinth** [comment] 2023-09-12 15:54
Testing it myself confirms what I've said above - Macaw's Roof double-slabs drop only a single slab even if KleeSlabs is not installed. This is not an issue in KleeSlabs, as KleeSlabs does not alter the behaviour of slabs it does not specifically add support for. This needs to be fixed in the two affected individual mods.

**Closed as not planned by BlayTheNinth** 2023-09-12 15:54 UTC
Labels: Bug, Caused by Another Mod
